sfdx-source/wesli/main/default/objects/WESLI_Settings__c/WESLI_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WESLI Settings</label>
</CustomObject>

sfdx-source/wesli/main/default/objects/WESLI_Settings__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/wesli/main/default/objects/WESLI_Settings__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/wesli/main/default/objects/WESLI_Settings__c/fields/Login_URL__c.field-meta.xml
<CustomField>
    <fullName>Login_URL__c</fullName>
    <label>Login URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/wesli/main/default/objects/WESLI_Settings__c/fields/Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URL__c</fullName>
    <label>Redirect URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

sfdx-source/wesli/main/default/classes/WesliOauth.cls
public class WesliOauth{  

    @remoteAction
    public static oauthsettings getOauthSettings(){
      return new oauthsettings();
    }
    
    public class oauthsettings{      
       public string clientId{get; set;}
       public String clientSecret{get; set;}
       public String redirectUri{get; set;}
       public string loginUrl{Get; set;}
            
        public oauthsettings(){
           WESLI_Settings__c settings = WESLI_Settings__c.getInstance();
           this.clientId = settings.Client_Id__c;
           this.clientSecret = settings.Client_Secret__c;
           this.redirectUri = settings.Redirect_URL__c;
           this.loginUrl = settings.Login_URL__c;
        }
    }
}